# Generated by Django 4.2.25 on 2026-01-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientaccesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
