# Generated by Django 4.2.25 on 2026-01-06 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eclinic', '0008_globalmedication_clinicinventory_global_medication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_source', models.CharField(choices=[('admin_created', 'Created by Admin'), ('consultation', 'Via Consultation'), ('self_registered', 'Self Registered'), ('migrated', 'Migrated from existing data')], default='admin_created', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_patients', to='eclinic.clinic')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_clinics', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, help_text='Admin who registered this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_clinic_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinic Patient',
                'verbose_name_plural': 'Clinic Patients',
                'db_table': 'clinic_patients',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['clinic', 'is_active'], name='clinic_pati_clinic__6453d2_idx'), models.Index(fields=['patient', 'is_active'], name='clinic_pati_patient_91d6ca_idx')],
                'unique_together': {('clinic', 'patient')},
            },
        ),
    ]
